import { createUseStyles } from 'react-jss';

import COLORS from '../../constants/COLORS';
import { hexToRgbA, rem } from '../../utils/jss';
import BREAKPOINTS from '../../constants/BREAKPOINTS';

export default createUseStyles({
  primary: { color: COLORS.primary },
  teaser: { textAlign: 'center', paddingTop: rem(32) },
  teaserTitle: {
    margin: 0,
    fontWeight: 900,
    fontSize: rem(64),
    lineHeight: rem(88),
  },
  teaserDescription: {
    fontWeight: 600,
    fontSize: rem(24),
    lineHeight: rem(40),
    margin: [rem(24), 'auto', 0],
  },
  coverImage: {
    width: '100%',
    height: rem(586),
    marginTop: rem(96),
    backgroundImage: 'url(/static/images/about-us/teaser.png)',
    backgroundSize: 'cover',
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'center',
  },
  menuScrollableLayout: { paddingTop: rem(120), paddingBottom: rem(96) },
  introduceTitle: {
    fontWeight: 900,
    fontSize: rem(56),
    lineHeight: rem(72),
    cursor: 'pointer',
    '&:nth-of-type(1)': { marginBottom: rem(24), marginTop: 0 },
    '&:nth-of-type(2)': { marginBottom: rem(40), marginTop: rem(160) },
    '&:nth-of-type(3)': { marginBottom: rem(64), marginTop: rem(160) },
  },
  aboutText: { fontSize: rem(24), lineHeight: rem(40) },
  aboutCompany: {
    marginTop: rem(72),
    marginBottom: rem(32),
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    boxSizing: 'border-box',
    backgroundColor: COLORS.bgGray,
    padding: [rem(64), rem(80), rem(109)],
    borderLeft: `1px solid ${COLORS.primary}`,
  },
  aboutCompanySummary: {
    flex: '50%',
    '&:nth-child(3), &:nth-child(4)': { marginTop: rem(85) },
  },
  aboutCompanyValue: {
    fontWeight: 600,
    fontSize: rem(48),
    lineHeight: rem(56),
    marginTop: 0,
    marginBottom: rem(12),
  },
  aboutCompanyLabel: { margin: 0, fontSize: rem(16), lineHeight: rem(24) },
  historyCompany: {},
  historyMark: {
    zIndex: 1,
    display: 'inline-block',
    width: rem(6),
    height: rem(6),
    borderRadius: rem(1),
    verticalAlign: 'middle',
    backgroundColor: COLORS.primary,
    transform: 'rotate(45deg)',
  },
  historySummary: {
    display: 'flex',
    '&:first-child > $historyYear': {
      '&::after': { top: rem(16) },
      '& > $historyMark': {
        width: rem(6),
        height: rem(6),
        right: rem(-4),
        '&::before, &::after': {
          content: '""',
          position: 'absolute',
          top: '50%',
          left: '50%',
          transform: 'translate(-50%, -50%)',
        },
        '&::before': {
          width: rem(16),
          height: rem(16),
          borderRadius: rem(2),
          backgroundColor: hexToRgbA(COLORS.primary, 0.1),
        },
        '&::after': {
          width: rem(24),
          height: rem(24),
          borderRadius: rem(3),
          backgroundColor: hexToRgbA(COLORS.primary, 0.05),
        },
      },
    },
    '&:last-child > $historyDescriptions': { paddingBottom: rem(24) },
  },
  historyYear: {
    paddingRight: rem(68),
    marginRight: rem(113),
    fontWeight: 900,
    fontSize: rem(18),
    lineHeight: rem(32),
    position: 'relative',
    '&::after': {
      content: '""',
      position: 'absolute',
      width: 1,
      height: '100%',
      backgroundColor: COLORS.borderGray,
      right: rem(-2),
      top: 0,
    },
    '& > $historyMark': {
      width: rem(4),
      height: rem(4),
      position: 'absolute',
      top: rem(12),
      right: rem(-3.25),
    },
  },
  historyDescriptions: {
    flex: 1,
    margin: 0,
    listStyleType: 'none',
    padding: [0, 0, rem(76)],
  },
  historyItem: {
    fontSize: rem(18),
    lineHeight: rem(32),
    position: 'relative',
    paddingLeft: rem(20),
    '& + $historyItem': { marginTop: rem(24) },
    '& > $historyMark': {
      position: 'absolute',
      top: rem(12),
      left: 0,
    },
  },
  members: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
  },
  member: {
    width: rem(205),
    textAlign: 'center',
    flex: `${100 / 3}%`,
    marginBottom: rem(64),
  },
  memberAvatar: {
    width: rem(205),
    height: rem(205),
    margin: [0, 'auto'],
    borderRadius: '50%',
    overflow: 'hidden',
    backgroundSize: 'cover',
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'center',
  },
  memberName: {
    marginTop: rem(24),
    marginBottom: 0,
    fontWeight: 900,
    fontSize: rem(24),
    lineHeight: rem(32),
  },
  memberRole: {
    margin: 0,
    fontWeight: 'bold',
    fontSize: rem(16),
    lineHeight: rem(24),
    color: COLORS.primary,
  },
  starting: {
    width: '100%',
    height: rem(360),
    backgroundImage: 'url(/static/images/about-us/get-start-bg.png)',
    backgroundSize: 'cover',
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'center',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  startingTitle: {
    margin: 0,
    fontWeight: 900,
    fontSize: rem(56),
    lineHeight: rem(72),
    color: COLORS.textWhite,
  },
  startingCTA: { marginLeft: rem(80) },

  [`@media only screen and (max-width: ${BREAKPOINTS.maxSm}px)`]: {
    teaserTitle: { fontSize: rem(40), lineHeight: rem(48) },
    teaserDescription: {
      fontSize: rem(16),
      lineHeight: rem(24),
      marginTop: rem(16),
    },
    coverImage: {
      marginTop: rem(48),
      backgroundImage: 'url(/static/images/about-us/teaser-mobile.png)',
    },
    menuScrollableLayout: { paddingTop: rem(48) },
    introduceTitle: {
      textAlign: 'center',
      fontSize: rem(40),
      lineHeight: rem(48),
      '&:nth-of-type(1)': { marginBottom: rem(16) },
      '&:nth-of-type(2)': { marginBottom: rem(48), marginTop: rem(64) },
      '&:nth-of-type(3)': { marginBottom: rem(48), marginTop: rem(64) },
    },
    aboutText: { textAlign: 'center', fontSize: rem(16), lineHeight: rem(24) },
    aboutCompany: { marginTop: rem(40), padding: rem(40) },
    aboutCompanySummary: {
      '&:nth-child(3), &:nth-child(4)': { marginTop: rem(64) },
    },
    aboutCompanyValue: {
      fontSize: rem(32),
      lineHeight: rem(40),
      marginBottom: rem(8),
    },
    aboutCompanyLabel: { fontSize: rem(12), lineHeight: rem(16) },
    historyYear: { paddingRight: rem(29), marginRight: rem(29) },
    historyDescriptions: { paddingBottom: rem(34) },
    historyItem: {
      fontSize: rem(16),
      lineHeight: rem(24),
      paddingLeft: 0,
      '& + $historyItem': { marginTop: rem(16) },
      '& > $historyMark': { display: 'none' },
    },
    member: { flex: '100%' },
    starting: {
      flexDirection: 'column',
      height: rem(280),
      backgroundImage: 'url(/static/images/about-us/get-start-bg-mobile.png)',
    },
    startingTitle: { fontSize: rem(32), lineHeight: rem(48) },
    startingCTA: {
      padding: [0, rem(32)],
      marginLeft: 0,
      marginTop: rem(24),
      boxShadow: '2px 4px 12px rgba(0, 0, 0, 0.15)',
    },
  },
});
