import { createUseStyles } from 'react-jss';

import COLORS from '../../constants/COLORS';
import { hexToRgbA, rem } from '../../utils/jss';
import BREAKPOINTS from '../../constants/BREAKPOINTS';

export default createUseStyles({
  content: { display: 'flex', flexWrap: 'wrap', maxWidth: rem(1270) },
  category: {
    flex: '100%',
    fontWeight: 600,
    fontSize: rem(24),
    lineHeight: rem(16),
    marginTop: 0,
    marginBottom: rem(16),
    color: COLORS.primary,
  },
  title: {
    flex: '100%',
    fontWeight: 900,
    fontSize: rem(56),
    lineHeight: rem(88),
    letterSpacing: '0.01em',
    marginTop: 0,
    marginBottom: rem(24),
    position: 'relative',
    textIndent: rem(32),
    '&::before': {
      content: '" "',
      top: rem(32),
      left: 0,
      position: 'absolute',
      width: rem(20),
      height: rem(20),
      backgroundColor: COLORS.primary,
      borderRadius: rem(4),
      transform: 'rotate(45deg)',
    },
  },
  summary: {
    flex: '0 0 60%',
    display: 'flex',
    marginBottom: rem(40),
    justifyContent: 'space-between',
  },
  author: { display: 'flex', alignItems: 'center' },
  authorImageWrapper: {
    overflow: 'hidden',
    width: rem(56),
    height: rem(56),
    flex: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    position: 'relative',
    border: `1px solid ${hexToRgbA(COLORS.borderBlack01, 0.3)}`,
  },
  authorImage: {
    width: '100%',
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
  },
  authorInfo: { marginLeft: rem(16), fontWeight: 900 },
  authorName: {
    fontSize: rem(18),
    lineHeight: rem(28),
    margin: 0,
    color: COLORS.primary,
  },
  lastUpdated: { fontSize: rem(12), lineHeight: rem(16), margin: 0 },
  sharing: { display: 'flex', alignItems: 'center' },
  sharingLabel: {
    fontWeight: 900,
    fontSize: rem(14),
    lineHeight: rem(24),
    margin: 0,
  },
  sharingIcon: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: rem(16),
    width: rem(32),
    height: rem(32),
    flex: 'none',
    borderRadius: '50%',
    cursor: 'pointer',
    position: 'relative',
    backgroundColor: COLORS.bgBlack01,
    '& > [class^=icon-]': { color: COLORS.textWhite, fontSize: rem(16) },
  },
  sharingPopup: {
    zIndex: 20,
    display: 'block',
    position: 'absolute',
    listStyle: 'none',
    margin: 0,
    right: 0,
    top: rem(40),
    backgroundColor: COLORS.bgWhite,
    borderRadius: rem(8),
    padding: [rem(12), 0],
    minWidth: rem(220),
    maxWidth: rem(300),
    maxHeight: rem(250),
    overflow: 'auto',
    boxShadow: '2px 4px 25px rgba(0, 0, 0, 0.25)',
  },
  sharingPopupItem: {
    padding: [rem(8), rem(16)],
    cursor: 'pointer',
    fontWeight: 400,
    fontSize: rem(16),
    lineHeight: rem(24),
    color: COLORS.textBlack01,
    '&:hover, &.active': {
      backgroundColor: COLORS.bgGray,
      color: COLORS.primary,
    },
  },
  sharingPopupLink: { display: 'flex', width: '100%' },
  sharingPopupIcon: {
    marginRight: rem(11),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: rem(24),
    height: rem(24),
    flex: 'none',
    borderRadius: '50%',
    backgroundColor: COLORS.bgBlack01,
    '& > [class^=icon-]': { color: COLORS.textWhite, fontSize: rem(12) },
  },
  thumbnailWrapper: { flex: '0 0 60%', textAlign: 'center' },
  thumbnail: { display: 'inline-block', maxWidth: '100%' },
  listRankings: {
    flex: '0 0 40%',
    paddingLeft: rem(40),
    marginBottom: rem(32),
    boxSizing: 'border-box',
  },
  newsContent: { flex: '0 0 60%', marginBottom: rem(40) },
  comments: { flex: '0 0 60%', marginBottom: rem(40) },

  [`@media only screen and (max-width: ${BREAKPOINTS.maxMd}px)`]: {
    comments: { flex: '100%', marginBottom: rem(32) },
  },
  [`@media only screen and (max-width: ${BREAKPOINTS.maxSm}px)`]: {
    content: {},
    category: { fontSize: rem(11), marginBottom: 0 },
    title: {
      fontSize: rem(24),
      lineHeight: rem(32),
      marginBottom: rem(16),
      textIndent: rem(16),
      '&::before': {
        top: rem(10),
        width: rem(12),
        height: rem(12),
        borderRadius: rem(2),
      },
    },
    sharingIcon: {
      width: rem(24),
      height: rem(24),
      '& > [class^=icon-]': { fontSize: rem(12) },
    },
    summary: { flex: '100%', marginBottom: rem(16) },
    authorImageWrapper: { width: rem(36), height: rem(36) },
    authorImage: { maxWidth: rem(24) },
    authorInfo: { marginLeft: rem(8) },
    authorName: { fontSize: rem(14), lineHeight: rem(20) },
    lastUpdated: { fontSize: rem(11) },
    sharingLabel: { display: 'none' },
    thumbnailWrapper: { flex: '1000%', marginBottom: rem(50) },
    listRankings: { flex: '100%', paddingLeft: 0 },
    newsContent: { flex: '100%', marginBottom: rem(32) },
  },
});
