.service:build:
  stage: build
  script:
    - export SERVICE_VERSION=$(cat api/${SERVICE_NAME}/package.json | jq -r .version)
    - export DOCKER_CLIENT_TIMEOUT=120
    - export COMPOSE_HTTP_TIMEOUT=120
    - docker login -u gitlab-ci-token -p "${CI_BUILD_TOKEN}" ${DOCKER_REGISTRY_DOMAIN}
    - docker-compose build ${SERVICE_NAME}
    - docker-compose push ${SERVICE_NAME}
  dependencies: []
  tags:
    - docker

.service:test:
  stage: test
  script:
    - cd api/${SERVICE_NAME}
    - npm install
    - npm run test
  cache:
    paths:
      - api/${SERVICE_NAME}/node_modules
  dependencies: []
  tags:
    - node
    - test

.service:deploy:
  stage: deploy
  script:
    - eval `ssh-agent -s`
    - mkdir ${DOCKER_CERT_PATH}
    - echo "${DOCKER_CA}" > ${DOCKER_CERT_PATH}/ca.pem
    - echo "${DOCKER_CERT}" > ${DOCKER_CERT_PATH}/cert.pem
    - echo "${DOCKER_KEY}" > ${DOCKER_CERT_PATH}/key.pem
    - docker login -u ${DOCKER_REGISTRY_USER} -p "${DOCKER_REGISTRY_PASSWORD}" ${DOCKER_REGISTRY_DOMAIN}
    - export SERVICE_VERSION=$(cat api/${SERVICE_NAME}/package.json | jq -r .version)
    - docker pull ${DOCKER_REGISTRY_DOMAIN}/${SERVICE_NAME}:${SERVICE_VERSION}${IMAGE_SUFFIX}
    - docker-compose up -d --force-recreate ${SERVICE_NAME}
    - rm -rf ${DOCKER_CERT_PATH}
  tags:
    - docker
    - e2w

.service:mail-service:
  only:
    changes:
      - ci/service.yml
      - api/mail-service/**/*
  variables:
    SERVICE_NAME: mail-service

.service:notifications-service:
  only:
    changes:
      - ci/service.yml
      - api/notifications-service/**/*
  variables:
    SERVICE_NAME: notifications-service

.service:prospects-service:
  only:
    changes:
      - ci/service.yml
      - api/prospects-service/**/*
  variables:
    SERVICE_NAME: prospects-service

.service:contacts-service:
  only:
    changes:
      - ci/service.yml
      - api/contacts-service/**/*
  variables:
    SERVICE_NAME: contacts-service

.service:roles-service:
  only:
    changes:
      - ci/service.yml
      - api/roles-service/**/*
  variables:
    SERVICE_NAME: roles-service

.service:users-service:
  only:
    changes:
      - ci/service.yml
      - api/users-service/**/*
  variables:
    SERVICE_NAME: users-service

.service:admins-service:
  only:
    changes:
      - ci/service.yml
      - api/admins-service/**/*
  variables:
    SERVICE_NAME: admins-service

.service:auth-service:
  only:
    changes:
      - ci/service.yml
      - api/auth-service/**/*
  variables:
    SERVICE_NAME: auth-service

.service:vacancies-service:
  only:
    changes:
      - ci/service.yml
      - api/vacancies-service/**/*
  variables:
    SERVICE_NAME: vacancies-service

.service:files-service:
  only:
    changes:
      - ci/service.yml
      - api/files-service/**/*
  variables:
    SERVICE_NAME: files-service

.service:news-service:
  only:
    changes:
      - ci/service.yml
      - api/news-service/**/*
  variables:
    SERVICE_NAME: news-service
