.settings:only:dev:
  only:
    refs:
      - dev

.settings:only:stag:
  only:
    refs:
      - stag

.settings:only:prod:
  only:
    refs:
      - master

.settings:variables:dev:
  variables:
    DOCKER_REGISTRY_DOMAIN: ${DEV_DOCKER_REGISTRY_DOMAIN}
    DOCKER_REGISTRY_USER: ${DEV_DOCKER_REGISTRY_USER}
    DOCKER_REGISTRY_PASSWORD: ${DEV_DOCKER_REGISTRY_PASSWORD}
    DOCKER_CA: ${DEV_DOCKER_CA}
    DOCKER_CERT: ${DEV_DOCKER_CERT}
    DOCKER_KEY: ${DEV_DOCKER_KEY}
    TRAEFIK_DASHBOARD_DOMAIN: ${DEV_TRAEFIK_DASHBOARD_DOMAIN}
    TRAEFIK_AUTH: ${DEV_TRAEFIK_AUTH}
    MAILGUN_DOMAIN: ${DEV_MAILGUN_DOMAIN}
    MAILGUN_SECRET: ${DEV_MAILGUN_SECRET}
    MONGO_DB: ${DEV_MONGO_DB}
    MONGO_HOST: ${DEV_MONGO_HOST}
    MONGO_PORT: ${DEV_MONGO_PORT}
    MONGO_USER: ${DEV_MONGO_USER}
    MONGO_PASSWORD: ${DEV_MONGO_PASSWORD}
    SYSTEM_EMAIL: ${DEV_SYSTEM_EMAIL}
    ADMIN_EMAIL: ${DEV_ADMIN_EMAIL}
    SUPPORT_EMAIL: ${DEV_SUPPORT_EMAIL}
    MAIN_DOMAIN: ${MAIN_DOMAIN}
    CMS_DOMAIN: ${DEV_CMS_DOMAIN}
    LANDING_PAGE_DOMAIN: ${DEV_LANDING_PAGE_DOMAIN}
    GA_MEASUREMENT_ID: ${DEV_GA_MEASUREMENT_ID}
    GG_DRIVE_CLIENT_ID: ${DEV_GG_DRIVE_CLIENT_ID}
    GG_DRIVE_CLIENT_SECRET: ${DEV_GG_DRIVE_CLIENT_SECRET}
    GG_DRIVE_REFRESH_TOKEN: ${DEV_GG_DRIVE_REFRESH_TOKEN}
    NODE_ENV: development
    IMAGE_SUFFIX: -dev

.settings:variables:deploy:dev:
  variables:
    DOCKER_CERT_PATH: 'certs'
    DOCKER_HOST: 'tcp://${DEV_DOCKER_HOST}'
    DEPLOY_KEY: ${DEV_DEPLOY_KEY}
    DEPLOY_HOST: ${DEV_DEPLOY_HOST}

.settings:variables:stag:
  variables:
    DOCKER_REGISTRY_DOMAIN: ${STAG_DOCKER_REGISTRY_DOMAIN}
    DOCKER_REGISTRY_USER: ${STAG_DOCKER_REGISTRY_USER}
    DOCKER_REGISTRY_PASSWORD: ${STAG_DOCKER_REGISTRY_PASSWORD}
    DOCKER_CA: ${STAG_DOCKER_CA}
    DOCKER_CERT: ${STAG_DOCKER_CERT}
    DOCKER_KEY: ${STAG_DOCKER_KEY}
    TRAEFIK_DASHBOARD_DOMAIN: ${STAG_TRAEFIK_DASHBOARD_DOMAIN}
    TRAEFIK_AUTH: ${STAG_TRAEFIK_AUTH}
    MAILGUN_DOMAIN: ${STAG_MAILGUN_DOMAIN}
    MAILGUN_SECRET: ${STAG_MAILGUN_SECRET}
    MONGO_DB: ${STAG_MONGO_DB}
    MONGO_HOST: ${STAG_MONGO_HOST}
    MONGO_PORT: ${STAG_MONGO_PORT}
    MONGO_USER: ${STAG_MONGO_USER}
    MONGO_PASSWORD: ${STAG_MONGO_PASSWORD}
    SYSTEM_EMAIL: ${STAG_SYSTEM_EMAIL}
    ADMIN_EMAIL: ${STAG_ADMIN_EMAIL}
    SUPPORT_EMAIL: ${STAG_SUPPORT_EMAIL}
    MAIN_DOMAIN: ${MAIN_DOMAIN}
    CMS_DOMAIN: ${STAG_CMS_DOMAIN}
    LANDING_PAGE_DOMAIN: ${STAG_LANDING_PAGE_DOMAIN}
    GA_MEASUREMENT_ID: ${STAG_GA_MEASUREMENT_ID}
    GG_DRIVE_CLIENT_ID: ${STAG_GG_DRIVE_CLIENT_ID}
    GG_DRIVE_CLIENT_SECRET: ${STAG_GG_DRIVE_CLIENT_SECRET}
    GG_DRIVE_REFRESH_TOKEN: ${STAG_GG_DRIVE_REFRESH_TOKEN}
    NODE_ENV: staging
    IMAGE_SUFFIX: -stag

.settings:variables:deploy:stag:
  variables:
    DOCKER_CERT_PATH: 'certs'
    DOCKER_HOST: 'tcp://${STAG_DOCKER_HOST}'
    DEPLOY_KEY: ${STAG_DEPLOY_KEY}
    DEPLOY_HOST: ${STAG_DEPLOY_HOST}

.settings:variables:prod:
  variables:
    DOCKER_REGISTRY_DOMAIN: ${PROD_DOCKER_REGISTRY_DOMAIN}
    DOCKER_REGISTRY_USER: ${PROD_DOCKER_REGISTRY_USER}
    DOCKER_REGISTRY_PASSWORD: ${PROD_DOCKER_REGISTRY_PASSWORD}
    DOCKER_CA: ${PROD_DOCKER_CA}
    DOCKER_CERT: ${PROD_DOCKER_CERT}
    DOCKER_KEY: ${PROD_DOCKER_KEY}
    TRAEFIK_DASHBOARD_DOMAIN: ${PROD_TRAEFIK_DASHBOARD_DOMAIN}
    TRAEFIK_AUTH: ${PROD_TRAEFIK_AUTH}
    MAILGUN_DOMAIN: ${PROD_MAILGUN_DOMAIN}
    MAILGUN_SECRET: ${PROD_MAILGUN_SECRET}
    MONGO_DB: ${PROD_MONGO_DB}
    MONGO_HOST: ${PROD_MONGO_HOST}
    MONGO_PORT: ${PROD_MONGO_PORT}
    MONGO_USER: ${PROD_MONGO_USER}
    MONGO_PASSWORD: ${PROD_MONGO_PASSWORD}
    SYSTEM_EMAIL: ${PROD_SYSTEM_EMAIL}
    ADMIN_EMAIL: ${PROD_ADMIN_EMAIL}
    SUPPORT_EMAIL: ${PROD_SUPPORT_EMAIL}
    MAIN_DOMAIN: ${MAIN_DOMAIN}
    CMS_DOMAIN: ${PROD_CMS_DOMAIN}
    LANDING_PAGE_DOMAIN: ${PROD_LANDING_PAGE_DOMAIN}
    GA_MEASUREMENT_ID: ${PROD_GA_MEASUREMENT_ID}
    GG_DRIVE_CLIENT_ID: ${PROD_GG_DRIVE_CLIENT_ID}
    GG_DRIVE_CLIENT_SECRET: ${PROD_GG_DRIVE_CLIENT_SECRET}
    GG_DRIVE_REFRESH_TOKEN: ${PROD_GG_DRIVE_REFRESH_TOKEN}
    NODE_ENV: production
    IMAGE_SUFFIX: -prod

.settings:variables:deploy:prod:
  variables:
    DOCKER_CERT_PATH: 'certs'
    DOCKER_HOST: 'tcp://${PROD_DOCKER_HOST}'
    DEPLOY_KEY: ${PROD_DEPLOY_KEY}
    DEPLOY_HOST: ${PROD_DEPLOY_HOST}